packages:
  - 'packages/*'
  - 'packages/**'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  es5-ext: true
  esbuild: true
  nx: true
  unrs-resolver: true
linkWorkspacePackages: true
dedupeInjectedDeps: false
onlyBuiltDependencies:
  - better-sqlite3
minimumReleaseAgeExclude:
  - '@ghentcdh/crouton-api'
  - '@ghentcdh/crouton-core'
  - '@ghentcdh/crouton-vue'
  - '@ghentcdh/create-crouton'
