packages:
  - 'packages/*'
  - 'packages/**'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  es5-ext: true
  esbuild: true
  nx: true
  unrs-resolver: true
linkWorkspacePackages: true
dedupeInjectedDeps: false
onlyBuiltDependencies:
  - better-sqlite3
minimumReleaseAgeExclude:
  - '@ghentcdh/crouton-api@0.0.1-alpha.37 || 0.0.1-alpha.38'
  - '@ghentcdh/crouton-cli@0.0.1-alpha.37 || 0.0.1-alpha.38'
  - '@ghentcdh/crouton-core@0.0.1-alpha.37 || 0.0.1-alpha.38'
  - '@ghentcdh/crouton-forms-vue@0.0.1-alpha.37 || 0.0.1-alpha.38'
  - '@ghentcdh/crouton-vue@0.0.1-alpha.37 || 0.0.1-alpha.38'

overrides:
  '@ghentcdh/crouton-forms-vue': link:../crouton/packages/crouton-forms-vue
  '@ghentcdh/crouton-vue': link:../crouton/packages/crouton-vue
  '@ghentcdh/crouton-cli': link:../crouton/packages/crouton-cli
  '@ghentcdh/crouton-api': link:../crouton/packages/crouton-api/dist
